name: Deploy
on:
    push:
        branches:
            - prod

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3
            - name: deploy para meu hosting
              uses: easingthemes/ssh-deploy@main
              env: 
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                ARGS: "-rlgoDzvc -i --delete"
                SOURCE: "laravel/"
                REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                REMOTE_USER: ${{ secrets.REMOTE_USER }}
                REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
                TARGET: ${{ secrets.REMOTE_TARGET }}
